version: '3.8'

services:
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: .
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:
